title: www.larswander.com
email: notmine@lwander.com
description: >
  Math & Computers
baseurl: "" 
url: "https://www.larswander.com" # the base hostname & protocol for your site
github_username: lwander

# Build settings
markdown: kramdown
permalink: /posts/:title.html
