title: lwander
email: notmine@lwander.com
description: >
  Math & Computers
baseurl: "" 
url: "http://lwander.github.io" # the base hostname & protocol for your site
github_username: lwander

# Build settings
markdown: kramdown
permalink: /posts/:title.html
